ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: "quarterly"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: name-tests-test
    args: ["--pytest-test-first"]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.270"
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]

- repo: https://github.com/psf/black
  rev: "23.3.0"
  hooks:
  - id: black-jupyter

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: "v2.2.0"
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.4"
  hooks:
  - id: codespell
    args: ["-L", "nd,unparseable,compiletime"]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.9.0.2"
  hooks:
  - id: shellcheck

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v3.0.0-alpha.9-for-vscode"
  hooks:
    - id: prettier
      types_or: [json]
